### ISSUE TITLE
Stress testing: need way to throw lots of clients against server

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#106]
Basic idea is lots of clients, in Python threads, running the simulation steps in test_pseudoclient 

First step - defining that simulation is done, 

Next step is Dan adding a harness

Challenge is assumptions in test_pseudoclient -> conftest -> __init__ that its using `server`

**Comment by danaronson** [comment]
we left in the test harness, but added threading. @mitra42 did it work ok?

**Comment by mitra42** [comment]
yes - working - now broken at my end #112 so can close this.
