### ISSUE TITLE
Multi: Need a way to share config files

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#3]
I'm not sure the easiest way to do this, but maybe a default config file that has a URL where to read one from at startup ?

**Comment by danaronson** [comment]
don't understand.  What URL?

**Comment by mitra42** [comment]
Note the "Multi" prefix (which I didn't explain), meaning only when we had multiple servers .... 

I was thinking that we would have a config file - maybe sitting in GIT - and then each server would at startup,  load a default config file, which could be standalone, but could instead contain for example `{ redirect: "https://github.com/xxxx/config.py"  }` - in which case it would fetch and install that config file instead.   

Just an idea ... there may be alternative ways to do that .

**Comment by danaronson** [comment]
got it

**Comment by danaronson** [comment]
#11
