### ISSUE TITLE
Getting synchronization to work?

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#41]
Dan - I see there is some sync functionality - is the peering working, and if not maybe list here any steps needed before we can test multi-server syncing, 

I'm not sure how we'd run a test for this - probably require two servers, and check the 2nd one gets the files, I'd be happy just if we tested it manually, and tested via test_sync that the protocol works.

**Comment by danaronson** [comment]
i tested it by hand at one point.  Since a fixture can only be used once, you could write another fixture called another_server (or something) in conftest which could allow you to have two servers.

**Comment by mitra42** [comment]
Dan - are you still on this one ?

**Comment by danaronson** [comment]
sure

**Comment by mitra42** [comment]
I think this is working ? Is this ready to close ?
