### ISSUE TITLE
sync_body undefined servers_file_name

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#46]
In sync_body servers_file_name isn't defined. 

(Note I'm in the process of renaming it to servers_file_path for consistency as I got bitten twice by the difference between a file_name and a file_path, but that isn't the problem here, where its not defined and I'm not sure where it should be getting it from

**Comment by danaronson** [comment]
I don't understand the problem.  It's a global... 
https://github.com/mitra42/bct-server/blob/fc151ff3b7ab958c546718b424b736f06d6e9d22/server.py#L56

**Comment by mitra42** [comment]
Oh - ok, missed that.
