### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by danaronson** [mitra42/bct-server#5]
integrate CI (circleci or other)

**Comment by danaronson** [comment]
@mitra42 can you setup the project in circleci (I believe that only the project admin can do this).  I should be able to take it from there:  https://app.circleci.com/projects/project-dashboard/github/mitra42/

**Comment by mitra42** [comment]
I've clicked through authorized and followed the obvious pathway till it does a build and fails. 
Over to you ... 
Let me know if you need me to do anything, could do a screen share etc if it needs my perms.

**Comment by mitra42** [comment]
I notice its branch builds off master rather than develop but presume you are used to configuring one of these ?

**Comment by danaronson** [comment]
it’ll run for every branch  that is pushed.

—dan

**Comment by danaronson** [comment]
integrated and ready for #35
