### ISSUE TITLE
Dates < <= or what

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#57]
(copied from Slack)
So two thoughts…..
* for real use, (not testing) then searching for records with `date < now` would work. It would only miss events that happened at the same second, and would send them at the next poll.
* For testing, instead of an HTTP header, we could possibly use the “testing” flag, and use incremental times, or more easily (and following the principle of not having testing and normal behave differently) put in 1-second delays between pings to the server,.

Would that cause anything to be missed, or duplicated. I don’t think so

**Comment by mitra42** [comment]
My original 'since < date' fails because it misses anything that came in on the same second as the poll, but after it.

**Comment by danaronson** [comment]
I would prefer a header, that way we can actually force known uses and not
rely on variability.  Often in these kinds of tests, time is mocked anyway

**Comment by mitra42** [comment]
Was merged in #58
