### ISSUE TITLE
Refactor: ID and Spatial storage

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#61]
On discussion it was felt ...
Move some of the functionality onto the ContactDict object
Move the UpdateTokenIdIdx into ContactDict, and interact with it via methods of ContactDict
Similarly Move the UpdateTokenGeoIdx into SpatialIndex, and interact with it via methods of SpatialIndex

Available for Dan or me to pick up - probably Dan

**Comment by danaronson** [comment]
I'm actually doing this to include NOT storing the geo object in the rtree database, but storing it also on disk in the same manner that the contacts are stored.  There is some good refactoring to do here.  I'm also using a python shelf object and sortedlist from the collections library to make everything more efficient.
