### ISSUE TITLE
Minor discrepancies between docs and code

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#63]
I'm going through and writing up the protocol doc, documenting discrepancies here.

- scan/status response
  - doc says `until` code does `now` 
    - I suggest we use `until` or `now`, because (see #62) this might not be now if the scale is too large  - this is in #85 
  - [x] spec says `contact_ids` and we send back `ids` 
    - I suggest we switch to `contact_ids`
  - [x] Should geolocations or ids contain durations ?
    - question for Jamison.

**Comment by danaronson** [comment]
I agree with all.

**Comment by mitra42** [comment]
- sync
  - as for scan/status it uses `now` instead of `until`

**Comment by mitra42** [comment]
- [ ] Update process doesn't quite match that in the spec - see #55

**Comment by mitra42** [comment]
- Jamison suggested field name conventions in the new proto doc
  - [ ] Decide on which to use
  - [ ] Check spec conforms
  - [ ] Massive code rename
