### ISSUE TITLE
status/scan bounding box too big

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#65]
We need to handle bounding box requests being too large. 
I'm not sure what size is to be fixed at - maybe 2DP (1km) and this might need discussing.

**Comment by danaronson** [comment]
I think the size should be parameterized.  I think a 400 response with a
json error description in the body.

**Comment by mitra42** [comment]
Decision on size in #68 - we'll implement an error if its >2DP (for now)

**Comment by mitra42** [comment]
Merged in PR#79
