### ISSUE TITLE
Discuss what additional fields want in status/send contacts

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#66]
We have a place holder for additional fields, but never discussed with Jamison, e.g. duration, location. (I think we want duration but not location).

**Comment by jmday** [comment]
Definitely don't want to store a "location" associated with any "close contact" ids.

**Comment by mitra42** [comment]
Do you want duration? Or just leave it to the client to design yes/no ?

**Comment by mitra42** [comment]
- [ ] write test to check behavior with unknown fields in various places

**Comment by mitra42** [comment]
Result of conversation with @jmday 

- Location just needs: lat, long, starttime and endtime
  - [x] spec
  - [ ] code
- ID needs duration (accurate to one minute) 
  - [ ] spec
  - [ ] code

**Comment by mitra42** [comment]
Note - spec changes were required but not code since unrecognized fields were stored and passed through
