### ISSUE TITLE
Storage and retrieval size for GeoLocations

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#68]
We have discussed storing obfuscated GeoData and retrieving via a bigger bounding box, those sizes were left TBD, maybe now is the time to discuss ... 

1 degree of latitude or longitude at the equator is about 100 km. 
So 4DP of lat/long would give us approx 100,000/10,000 = 10meter resolution. That is probably sufficient to for example resolve to a single store, and if we request at 2DP that would be a 1km box. 

Thoughts ....

**Comment by jmday** [comment]
Our current implementation uses lat/long each rounded to 4DP for establishing a "visit" when the device has stayed within that boundary for 2 min.

We should probably think through what the largest bounding_box we would be willing to provide results from would be. For starters, returning the 2DP box for each set of contained 4DP visits might make sense (max of 100 possible results per visit). Using a bounding_box of 1DP would get us 10km^2 and max of 10,000 results per visit, which feels big?

**Comment by mitra42** [comment]
Ok - looks like this is all client-size - I'll update the doc.

**Comment by mitra42** [comment]
Doc handles this and serve now specifies acceptable sizes in the /signon
