### ISSUE TITLE
add real bucketing and search for green

### ISSUE THREAD

**Issue by danaronson** [mitra42/bct-server#7]
currently the code is a dumb O(n) algorithm.  Not sure the right data structure yet.

**Comment by mitra42** [comment]
Am I missing something - there is no code pushed to do a /green retrieval of ids, but given the data structure it looks O(n) on the in-memory structure, but O(Log(n)) if got from files.  

If we are concerned about size of memory usage for ids[] then possibly we need a config boolean as to whether to use memory or not ? 

Also .... maybe just mirror the file data structure in memory, that would give us O(log(n)) in mem as well, and the code would be simpler so  ids[hex_string] = now, would become ids[first_level][second_level][third_level] = now

**Comment by danaronson** [comment]
code is in the PR:  https://github.com/mitra42/bct-server/pull/6

ooh, clever and nice simple idea for traversal.  Thanks.

--dan

**Comment by danaronson** [comment]
it's actually

ids[first_level][second_level][third_level][id] = now

**Comment by danaronson** [comment]
before I close out it's:

ids[first_level][second_level][third_level][id] = [date_1, date_2, date_3, ...]

where the dates are for unique JSON blobs that get received.
