### ISSUE TITLE
Add a signon endpoint

### ISSUE THREAD

**Issue by mitra42** [mitra42/bct-server#70]
Will add a signon endpoint - this will allow us to pass a number of pieces of information between client and server. It should run at startup and once a day.  Note there is intentionally no link between this request/response and status/send or status/scan 

There is a balance to be drawn here between providing info that makes the whole system work better, and so much info that privacy is violated.

Here is a straw-person, it might not strike the right balance.

Request fields (client to server)
- [ ] App name
- [ ] App version number
- [ ] Phone type
- [ ] Region
- [ ] Health provider
- [ ] Percentage up-time (how much time the phone has been on with the app running since last signon)

Response fields (server to client)
- [ ] App current version names and number(s)
- [ ] URL of messsaging (based on 
- [ ] Version number of any messaging (so client can tell if it needs to re-retrieve it)
- [ ] Bounding box decimal points (to use in status/scan) see #65 and #68 
- [ ] Prefix bits (multiple of 4) see #34 

Discussion of any of these can go in the comments,

**Comment by danaronson** [comment]
how are we encoding the ids?  I had thought that it was just as a hexstring in which case shoulding it by prefix bytes?

**Comment by mitra42** [comment]
The original EphIds are 128 bits I believe. Yes - we are using a hexstring, though I think that was probably a bad idea and that we should use something more compressed, which is why I'd rather keep this prefix spec as bits.

**Comment by danaronson** [comment]
ok, what do you want to use?

**Comment by mitra42** [comment]
- [x] Update spec
- [ ] Spec review by @jmday 
- [ ] Spec review by @danaronson 
- [ ] Code

**Comment by mitra42** [comment]
Live
